### ISSUE TITLE
Running `bv_maker doc` creates untracked files in the Git repository

### ISSUE THREAD

**Issue by ylep** [brainvisa/anatomist-gpl#11]
Running `bv_maker doc` creates untracked files in the Git repository::

	pyanatomist/doc/examples/fusion.tex
	pyanatomist/doc/examples/fusion.tex.minf
	pyanatomist/doc/examples/sphere.pyc
	pyanatomist/doc/sphinx/auto_examples/

We should:

- either, generate these files somewhere else (in a temporary location?)
- or, add them to `.gitignore` to stop the Git repository from being shown as dirty.

**Comment by denisri** [comment]
fixed by f5ae15732e2a5c0c591a597227f83f33a1b57b41 two years ago.
