### ISSUE TITLE
Linked cursor is not displayed anymore

### ISSUE THREAD

**Issue by nsouedet** [brainvisa/anatomist-gpl#12]
This issue seems to occur both on master and integration branches. It was reproduced on two different Ubuntu 16.04 computers with NVidia drivers. A consequence is that the value contained in a pixel can not be read anymore by clicking in a window.

**Comment by denisri** [comment]
Is it the same as brainvisa/anatomist-free#20 ? I could never reproduce this situation, so I can't work on it...

**Comment by nsouedet** [comment]
Duplicate with brainvisa/anatomist-free#20
