### ISSUE TITLE
Anatomist integration in Brainvisa block process run

### ISSUE THREAD

**Issue by Hboni** [brainvisa/anatomist-gpl#8]
Some of the pipelines that I use in brainvisa integrate Anatomist visualization for QC. For some time (couple of weeks), when I run one of these pipelines after the anatomist window closed, the process doesn't continue, it stays stuck at the process following, doing nothing, with the brain gif moving, but nothing happening.
After that, if I close the process, I can use Brainvisa. But if I close brainvisa, the BV window doesn't close, casa-distro doesn't finish, and if I force the end of the process in terminal (Ctrl + C), I can use my terminal, but the brainvisa window doesn't disappear. 

After closing the QC process, I've got those kinds of output in the terminal :

```
GL_ARB_texture_cube_map extension present
GL_EXT_texture_cube_map extension present
Number of texture units: 8
ATransformSet::unregisterObserver: ref 0xf400760 not found
[299.707, 299.707, 152.055, 0]
observable 0x10caf2e0 could not be removed from observer 0x10d11038
FusionObjects: 2, Fusion2DMethod
ATransformSet::unregisterObserver: ref 0x13832ad0 not found
origin and source UUID mismatch.
overriding transformation source referential
destination and destination UUID mismatch.
overriding transformation destination referential
ATransformSet::unregisterObserver: ref 0x13832ad0 not found
[299.707, 299.707, 152.055, 0]
observable 0xd7c28a0 could not be removed from observer 0xdc85878
FusionObjects: 2, Fusion2DMethod
ATransformSet::unregisterObserver: ref 0x10d499c0 not found
ATransformSet::unregisterObserver: ref 0x10da7500 not found
ATransformSet::unregisterObserver: ref 0x10da7500 not found
[299.707, 299.707, 152.055, 0]
observable 0x10caf2e0 could not be removed from observer 0x1382e448
FusionObjects: 2, Fusion2DMethod
ATransformSet::unregisterObserver: ref 0x13832ad0 not found
ATransformSet::unregisterObserver: ref 0x10caf1c0 not found
origin and source UUID mismatch.
overriding transformation source referential
destination and destination UUID mismatch.
overriding transformation destination referential
ATransformSet::unregisterObserver: ref 0x10caf1c0 not found
[299.707, 299.707, 152.055, 0]
observable 0xd7c28a0 could not be removed from observer 0x13926248
FusionObjects: 2, Fusion2DMethod
ATransformSet::unregisterObserver: ref 0x10da7500 not found
ATransformSet::unregisterObserver: ref 0xf3ebbf0 not found
ATransformSet::unregisterObserver: ref 0xf3ebbf0 not found
[299.707, 299.707, 152.055, 0]
config.setitem: leftRightDisplayed : 1
No icon for control MeasurementControl
observable 0xdc54250 could not be removed from observer 0xd790838
observable 0xdc42050 could not be removed from observer 0x13c8c3d8
observable 0x1391d640 could not be removed from observer 0x13c8c3d8
observable 0xeec2c00 could not be removed from observer 0xee2f8b8
observable 0x1391ecb0 could not be removed from observer 0xee2f8b8
```
(in this case I have 3 anatomist windows used)

I'm aware that the anatomist integration might not be well done in those pipelines, but my brainvisa wasn't blocked like that before.

One of the pipelines that create this type of error is the "Check raw data pipeline (PET)" in the nuclear imaging toolbox, with the "Nuclear Imaging quality check" process. I can transfer some test data if you want to try.

But first, I would like to check the anatomist integration in QC processes (for example), can you point me a process/example of good anatomist integration in brainvisa? Maybe I can fix it without you digging into NIT processes.

**Comment by denisri** [comment]
Does the pipeline run commandlines (context.system() or other subprocess.somethig) after anatomist interface is used ? If yes, it may be the same problem as https://github.com/brainvisa/anatomist-free/issues/17.
It was normally solved by brainvisa/anatomist-free@ebe5c4c202447874c1e1f82ebd6c5464de36b8e4. Have you updated and tried after this changeset ?

**Comment by Hboni** [comment]
The last update was at the beginning of the week. I didn't find any context.system() or subprocess. in the process/pipeline.

I updated anatomist-free, and it seems that I couldn't reproduce the bug, that's great! 
I didn't test all the cases, but if the bug appears again I'll reopen this issue.

Thanks @denisri

**Comment by denisri** [comment]
The symptoms looked similar, and if it doesn't show up any longer, there's a good chance it's the same problem, which has been solved :)
