### ISSUE TITLE
add hash() method in anatomist for python 3 ? 

### ISSUE THREAD

**Issue by manuegrx** [brainvisa/anatomist-gpl#9]
Hi everyone, 

Is it possible to add a hash() method ( __hash__() ) in anatomist in python 3  for the anatomist object (type anatomist.direct.api.AObject ) ? 
It seems that this method was a default method in python 2 and was working  in python 2 for anatomist object.

**Comment by denisri** [comment]
Yes, that could be helpful.

**Comment by denisri** [comment]
AItem.__hash__ was actually already defined, but doesn't seem to work. On an AObject I get obj.__hash__ as None (should be the function/method object), which I can't explain for now.

**Comment by sapetnioc** [comment]
There is a global id() function that can be used to implement the hash in
the same way as it is implemented in Python 2.

**Comment by denisri** [comment]
I have found the answer here: https://docs.python.org/3/reference/datamodel.html#object.__hash__
"A class that overrides __eq__() and does not define __hash__() will have its __hash__() implicitly set to None"
